// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: app/service/player/service.proto

package player

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	types "github.com/kubegames/kubegames-hall/app/service/player/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("app/service/player/service.proto", fileDescriptor_0d622ed18adb5c5e) }

var fileDescriptor_0d622ed18adb5c5e = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xdd, 0x4e, 0x13, 0x4f,
	0x14, 0xc0, 0xbb, 0x25, 0x7f, 0xf2, 0xcf, 0x2a, 0x28, 0x83, 0x9f, 0x25, 0x2e, 0xc3, 0x4a, 0x4c,
	0x24, 0xda, 0x11, 0x4c, 0x88, 0x21, 0xc6, 0x04, 0xbc, 0x20, 0x24, 0x92, 0x10, 0xf4, 0x8a, 0x0b,
	0x71, 0x76, 0x39, 0xcc, 0x4e, 0x28, 0x3b, 0xe3, 0xec, 0xb4, 0x0a, 0xc4, 0x0b, 0x8d, 0xf1, 0x01,
	0xf0, 0xc6, 0x47, 0xe0, 0x51, 0xb8, 0x34, 0xf1, 0xda, 0x04, 0xaa, 0x0f, 0xe0, 0x23, 0x98, 0xf9,
	0x58, 0x5b, 0x6c, 0xa9, 0x37, 0xdb, 0x9d, 0x39, 0xbf, 0x39, 0xbf, 0x73, 0xce, 0xa4, 0x1b, 0x62,
	0x2a, 0x25, 0x29, 0x40, 0xb5, 0x78, 0x0a, 0x44, 0x36, 0xe8, 0x1e, 0xa8, 0x72, 0x59, 0x97, 0x4a,
	0x68, 0x81, 0x46, 0xdd, 0xee, 0xa6, 0xdf, 0xad, 0x4d, 0xf7, 0x39, 0xa1, 0xf7, 0x24, 0x14, 0xee,
	0xe9, 0x4e, 0x39, 0xaa, 0xc1, 0x13, 0xc2, 0x84, 0x60, 0x0d, 0x20, 0x54, 0x72, 0x42, 0xf3, 0x5c,
	0x68, 0xaa, 0xb9, 0xc8, 0x4b, 0x0a, 0x77, 0x28, 0x26, 0x88, 0xdd, 0x4b, 0x9a, 0xdb, 0x76, 0xe5,
	0x89, 0xf9, 0x92, 0xb0, 0xcb, 0x74, 0x93, 0x41, 0xbe, 0x29, 0x24, 0xe4, 0x54, 0xf2, 0xd6, 0x1c,
	0x11, 0xd2, 0x66, 0xeb, 0xcd, 0x3c, 0xf7, 0x7d, 0x38, 0x1c, 0x59, 0xb3, 0xc5, 0x3d, 0x77, 0xa5,
	0xa2, 0xf7, 0x41, 0x78, 0x71, 0x19, 0xf4, 0x5a, 0x26, 0x72, 0x78, 0x2a, 0xb6, 0x00, 0x4d, 0xd5,
	0x7d, 0x67, 0xae, 0xee, 0xee, 0xd8, 0x3a, 0xbc, 0x6e, 0x42, 0xa1, 0x6b, 0xf1, 0x20, 0xa4, 0x90,
	0x22, 0x2f, 0x20, 0x9e, 0x39, 0x5c, 0xac, 0x26, 0x95, 0x0f, 0xdf, 0x7e, 0x7e, 0xae, 0x4e, 0xa2,
	0x5b, 0xe5, 0x44, 0x5a, 0xb3, 0x44, 0x1a, 0x94, 0xa4, 0x62, 0x0b, 0xc8, 0x81, 0x7d, 0x7f, 0x87,
	0x3e, 0x05, 0xe1, 0xa8, 0xab, 0x6a, 0x1d, 0x18, 0x2f, 0x34, 0x28, 0x74, 0xfb, 0xac, 0xe2, 0x6c,
	0xb4, 0xac, 0x63, 0x7a, 0x30, 0xe4, 0x2b, 0xb9, 0xdb, 0xa9, 0x24, 0x8a, 0x6f, 0xf6, 0x54, 0xa2,
	0x3c, 0xbf, 0x10, 0xcc, 0xa0, 0xfd, 0xf0, 0x82, 0x4b, 0xf2, 0x4c, 0x30, 0x9e, 0x23, 0xdc, 0x2f,
	0xbf, 0x0d, 0x95, 0x15, 0x4c, 0x0d, 0x20, 0xbc, 0xfe, 0x4e, 0x47, 0x3f, 0x11, 0x5f, 0xeb, 0xd1,
	0x37, 0x0c, 0x6c, 0xdc, 0x59, 0x18, 0xba, 0xe3, 0x2b, 0xf9, 0xb6, 0x40, 0x93, 0xfd, 0x12, 0x9b,
	0x48, 0x69, 0xc6, 0xe7, 0x03, 0x5e, 0x7c, 0xdd, 0x3a, 0xc7, 0xd0, 0xa5, 0x2e, 0x27, 0x37, 0xb9,
	0x45, 0xd9, 0xe5, 0x2a, 0xd5, 0x69, 0xd6, 0xbf, 0x4b, 0x1b, 0x1a, 0xd8, 0xa5, 0x27, 0xbc, 0x6c,
	0xc2, 0xca, 0xae, 0xc6, 0x97, 0xbb, 0x64, 0xbb, 0x86, 0x30, 0xad, 0x1d, 0x74, 0xae, 0x37, 0xcd,
	0xa8, 0x62, 0x70, 0xde, 0xf5, 0xba, 0xe8, 0x3f, 0xae, 0xb7, 0x84, 0xbc, 0x39, 0xb2, 0xe6, 0x1b,
	0xf1, 0x78, 0x97, 0x59, 0x79, 0xc8, 0xc8, 0x77, 0xca, 0xb9, 0x2e, 0xf3, 0x16, 0xf4, 0x9f, 0xab,
	0x89, 0x0c, 0x9c, 0xab, 0x03, 0xbc, 0xb0, 0x66, 0x85, 0x57, 0xe2, 0xee, 0xb9, 0x32, 0xde, 0x32,
	0xb2, 0xa5, 0x8f, 0xd5, 0xc3, 0xc5, 0xa3, 0x00, 0x91, 0x70, 0x6a, 0xa7, 0x99, 0x00, 0xa3, 0xbb,
	0x50, 0x60, 0xf3, 0xc4, 0x0e, 0xc5, 0x54, 0x72, 0x5c, 0xbc, 0xa1, 0x8c, 0x81, 0x9a, 0xf9, 0x2f,
	0x1c, 0x5a, 0x5d, 0x79, 0x31, 0x37, 0x34, 0x5b, 0x7f, 0xb0, 0xf1, 0x2a, 0x7c, 0x19, 0x8e, 0x2c,
	0x36, 0x75, 0x26, 0x14, 0xdf, 0xb7, 0xff, 0x58, 0xb4, 0xfa, 0x7f, 0x15, 0x3d, 0x32, 0x5b, 0x90,
	0x6b, 0x9e, 0xda, 0x3d, 0xac, 0xc5, 0x0e, 0xe4, 0xf7, 0xb0, 0x54, 0xb0, 0xcd, 0xdf, 0xc2, 0x16,
	0x4e, 0xf6, 0xf0, 0x12, 0x50, 0x05, 0x6a, 0xc1, 0xff, 0xe2, 0xc7, 0x16, 0x79, 0x52, 0x3b, 0x9b,
	0x0c, 0x57, 0x93, 0xf1, 0x70, 0xec, 0x6f, 0x43, 0xe5, 0xf8, 0x34, 0xaa, 0x9c, 0x9c, 0x46, 0xc1,
	0xaf, 0xd3, 0x28, 0x38, 0x6a, 0x47, 0xc1, 0x71, 0x3b, 0x0a, 0xbe, 0xb6, 0xa3, 0xe0, 0xa4, 0x1d,
	0x05, 0x5f, 0x7e, 0x44, 0x95, 0x8d, 0x79, 0xc6, 0x75, 0xd6, 0x4c, 0xea, 0xa9, 0xd8, 0x25, 0x7f,
	0x1a, 0xea, 0xbc, 0xdd, 0xcf, 0x68, 0xa3, 0x41, 0x7a, 0x3f, 0x7c, 0xc9, 0xb0, 0xfd, 0xda, 0x3c,
	0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x34, 0xec, 0xf8, 0x53, 0x47, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlayerServiceClient is the client API for PlayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerServiceClient interface {
	//获取验证码
	GetPhoneCode(ctx context.Context, in *types.GetPhoneCodeRequest, opts ...grpc.CallOption) (*types.GetPhoneCodeResponse, error)
	//玩家注册
	PlayerRegister(ctx context.Context, in *types.PlayerRegisterRequest, opts ...grpc.CallOption) (*types.PlayerRegisterResponse, error)
	//玩家登录
	PlayerLogin(ctx context.Context, in *types.PlayerLoginRequest, opts ...grpc.CallOption) (*types.PlayerLoginResponse, error)
	//玩家信息
	PlayerInfo(ctx context.Context, in *types.PlayerInfoRequest, opts ...grpc.CallOption) (*types.PlayerInfoResponse, error)
	//玩家匹配
	PlayerMatch(ctx context.Context, in *types.PlayerMatchRequest, opts ...grpc.CallOption) (*types.PlayerMatchResponse, error)
	//玩家充值金币
	PlayerRecharge(ctx context.Context, in *types.PlayerRechargeRequest, opts ...grpc.CallOption) (*types.PlayerRechargeResponse, error)
	//玩家赠送金币
	PlayerGive(ctx context.Context, in *types.PlayerGiveRequest, opts ...grpc.CallOption) (*types.PlayerGiveResponse, error)
}

type playerServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlayerServiceClient(cc *grpc.ClientConn) PlayerServiceClient {
	return &playerServiceClient{cc}
}

func (c *playerServiceClient) GetPhoneCode(ctx context.Context, in *types.GetPhoneCodeRequest, opts ...grpc.CallOption) (*types.GetPhoneCodeResponse, error) {
	out := new(types.GetPhoneCodeResponse)
	err := c.cc.Invoke(ctx, "/player_service.PlayerService/GetPhoneCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) PlayerRegister(ctx context.Context, in *types.PlayerRegisterRequest, opts ...grpc.CallOption) (*types.PlayerRegisterResponse, error) {
	out := new(types.PlayerRegisterResponse)
	err := c.cc.Invoke(ctx, "/player_service.PlayerService/PlayerRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) PlayerLogin(ctx context.Context, in *types.PlayerLoginRequest, opts ...grpc.CallOption) (*types.PlayerLoginResponse, error) {
	out := new(types.PlayerLoginResponse)
	err := c.cc.Invoke(ctx, "/player_service.PlayerService/PlayerLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) PlayerInfo(ctx context.Context, in *types.PlayerInfoRequest, opts ...grpc.CallOption) (*types.PlayerInfoResponse, error) {
	out := new(types.PlayerInfoResponse)
	err := c.cc.Invoke(ctx, "/player_service.PlayerService/PlayerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) PlayerMatch(ctx context.Context, in *types.PlayerMatchRequest, opts ...grpc.CallOption) (*types.PlayerMatchResponse, error) {
	out := new(types.PlayerMatchResponse)
	err := c.cc.Invoke(ctx, "/player_service.PlayerService/PlayerMatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) PlayerRecharge(ctx context.Context, in *types.PlayerRechargeRequest, opts ...grpc.CallOption) (*types.PlayerRechargeResponse, error) {
	out := new(types.PlayerRechargeResponse)
	err := c.cc.Invoke(ctx, "/player_service.PlayerService/PlayerRecharge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) PlayerGive(ctx context.Context, in *types.PlayerGiveRequest, opts ...grpc.CallOption) (*types.PlayerGiveResponse, error) {
	out := new(types.PlayerGiveResponse)
	err := c.cc.Invoke(ctx, "/player_service.PlayerService/PlayerGive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServiceServer is the server API for PlayerService service.
type PlayerServiceServer interface {
	//获取验证码
	GetPhoneCode(context.Context, *types.GetPhoneCodeRequest) (*types.GetPhoneCodeResponse, error)
	//玩家注册
	PlayerRegister(context.Context, *types.PlayerRegisterRequest) (*types.PlayerRegisterResponse, error)
	//玩家登录
	PlayerLogin(context.Context, *types.PlayerLoginRequest) (*types.PlayerLoginResponse, error)
	//玩家信息
	PlayerInfo(context.Context, *types.PlayerInfoRequest) (*types.PlayerInfoResponse, error)
	//玩家匹配
	PlayerMatch(context.Context, *types.PlayerMatchRequest) (*types.PlayerMatchResponse, error)
	//玩家充值金币
	PlayerRecharge(context.Context, *types.PlayerRechargeRequest) (*types.PlayerRechargeResponse, error)
	//玩家赠送金币
	PlayerGive(context.Context, *types.PlayerGiveRequest) (*types.PlayerGiveResponse, error)
}

// UnimplementedPlayerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerServiceServer struct {
}

func (*UnimplementedPlayerServiceServer) GetPhoneCode(ctx context.Context, req *types.GetPhoneCodeRequest) (*types.GetPhoneCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPhoneCode not implemented")
}
func (*UnimplementedPlayerServiceServer) PlayerRegister(ctx context.Context, req *types.PlayerRegisterRequest) (*types.PlayerRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerRegister not implemented")
}
func (*UnimplementedPlayerServiceServer) PlayerLogin(ctx context.Context, req *types.PlayerLoginRequest) (*types.PlayerLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerLogin not implemented")
}
func (*UnimplementedPlayerServiceServer) PlayerInfo(ctx context.Context, req *types.PlayerInfoRequest) (*types.PlayerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerInfo not implemented")
}
func (*UnimplementedPlayerServiceServer) PlayerMatch(ctx context.Context, req *types.PlayerMatchRequest) (*types.PlayerMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerMatch not implemented")
}
func (*UnimplementedPlayerServiceServer) PlayerRecharge(ctx context.Context, req *types.PlayerRechargeRequest) (*types.PlayerRechargeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerRecharge not implemented")
}
func (*UnimplementedPlayerServiceServer) PlayerGive(ctx context.Context, req *types.PlayerGiveRequest) (*types.PlayerGiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerGive not implemented")
}

func RegisterPlayerServiceServer(s *grpc.Server, srv PlayerServiceServer) {
	s.RegisterService(&_PlayerService_serviceDesc, srv)
}

func _PlayerService_GetPhoneCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.GetPhoneCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetPhoneCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player_service.PlayerService/GetPhoneCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetPhoneCode(ctx, req.(*types.GetPhoneCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_PlayerRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.PlayerRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).PlayerRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player_service.PlayerService/PlayerRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).PlayerRegister(ctx, req.(*types.PlayerRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_PlayerLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.PlayerLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).PlayerLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player_service.PlayerService/PlayerLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).PlayerLogin(ctx, req.(*types.PlayerLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_PlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.PlayerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).PlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player_service.PlayerService/PlayerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).PlayerInfo(ctx, req.(*types.PlayerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_PlayerMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.PlayerMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).PlayerMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player_service.PlayerService/PlayerMatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).PlayerMatch(ctx, req.(*types.PlayerMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_PlayerRecharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.PlayerRechargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).PlayerRecharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player_service.PlayerService/PlayerRecharge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).PlayerRecharge(ctx, req.(*types.PlayerRechargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_PlayerGive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.PlayerGiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).PlayerGive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player_service.PlayerService/PlayerGive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).PlayerGive(ctx, req.(*types.PlayerGiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlayerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "player_service.PlayerService",
	HandlerType: (*PlayerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPhoneCode",
			Handler:    _PlayerService_GetPhoneCode_Handler,
		},
		{
			MethodName: "PlayerRegister",
			Handler:    _PlayerService_PlayerRegister_Handler,
		},
		{
			MethodName: "PlayerLogin",
			Handler:    _PlayerService_PlayerLogin_Handler,
		},
		{
			MethodName: "PlayerInfo",
			Handler:    _PlayerService_PlayerInfo_Handler,
		},
		{
			MethodName: "PlayerMatch",
			Handler:    _PlayerService_PlayerMatch_Handler,
		},
		{
			MethodName: "PlayerRecharge",
			Handler:    _PlayerService_PlayerRecharge_Handler,
		},
		{
			MethodName: "PlayerGive",
			Handler:    _PlayerService_PlayerGive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/service/player/service.proto",
}
