---
apiVersion: v1
kind: Namespace
metadata:
  name: nsq

---
apiVersion: v1
kind: Service
metadata:
  namespace: nsq
  name: nsqlookupd
spec:
  type: ClusterIP
  selector:
    app: nsqlookupd
  ports:
  - protocol: TCP
    port: 4160
    targetPort: 4160
    name: nsqlookupd-tcp
  - protocol: TCP
    port: 4161
    targetPort: 4161
    name: nsqlookupd-http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nsq
  name: nsqlookupd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsqlookupd
  template:
    metadata:
      labels:
        app: nsqlookupd
    spec:
      containers:
      - name: nsqlookupd
        image: nsqio/nsq:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        args:
        - /nsqlookupd

---
apiVersion: v1
kind: Service
metadata:
  namespace: nsq
  name: nsqadmin
spec:
  type: NodePort
  selector:
    app: nsqadmin
  ports:
  - protocol: TCP
    port: 4171
    targetPort: 4171
    nodePort: 30171

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nsq
  name: nsqadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsqadmin
  template:
    metadata:
      labels:
        app: nsqadmin
    spec:
      containers:
      - name: nsqadmin
        image: nsqio/nsq:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        args:
        - /nsqadmin --lookupd-http-address=nsqlookupd.nsq.svc:4161

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nsq
  name: nsqd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nsqd
  template:
    metadata:
      labels:
        app: nsqd
    spec:
      containers:
      - name: nsqd
        image: nsqio/nsq:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
               fieldPath: status.podIP
        ports:
        - containerPort: 4150
          name: tcp
        - containerPort: 4151
          name: http
        command:
        - /bin/sh
        - -c
        args:
        - /nsqd --lookupd-tcp-address=nsqlookupd.nsq.svc:4160 --broadcast-address=$POD_IP